### PR TITLE
Add Assert.true and Assert.false

### PR DESCRIPTION
**Pull request by mgold**
These boolean assertions are very useful. There is a similar ability in `elm-check` and we should support those upgrading.

Also, I don't have write access.

### CODE REVIEW

**Comment by rtfeldman** [comment]
Cool, although I think making it `true : String -> Assertion` and `false : String -> Assertion` makes sense; that default error message will never be useful, so it seems reasonable to make the "easy path" the one where you specify the error message yourself.

**Comment by mgold** [comment]
I liked being able to do `crazy thing |> Assert.true` and let the description of the test handle it. It's not a useful error message to read, but it's a useful error message to not have to write. And you can always do `onFail` or whatever.

**Comment by rtfeldman** [comment]
Given that `crazy thing |> Assert.true ""` is only 3 extra characters and no less helpful an error message than `"Expected True and got False"` (since neither tells you anything), seems like this is a reasonable convenience for the case where you actually do want a helpful message, no? 😉

**Comment by mgold** [comment]
Hmm, maybe. Do we filter out empty strings in the runners?

**Comment by rtfeldman** [comment]
For the record, I genuinely do use such assertions this way - if I have an assertion too complicated for `equal` or `lessThan` or whatever, I want to say "screw it, I'll give you a boolean and tell you what to output if it fails"

**Comment by rtfeldman** [comment]
We currently don't, but we could easily have them default to like "An assertion failed" or something.

**Comment by mgold** [comment]
> I'll give you a boolean and tell you what to output if it fails

How so?

**Comment by rtfeldman** [comment]
so like

``` elm
Assert.true (Model.isValid model) "resulting model wasn't valid"
```

**Comment by rtfeldman** [comment]
(where I want to avoid converting my entire `Model.isValid` function to a series of assertions)

**Comment by mgold** [comment]
Looking over [my code](https://github.com/mgold/elm-nonempty-list/blob/5364a78e43fd5758a7b851cf072468e1d1971052/test/Testing.elm), I don't think it would be so bad. Go ahead and add the string arg.

**Comment by rtfeldman** [comment]
done! http://package.elm-lang.org/packages/project-fuzzball/test/1.2.0/Assert

**Pull request merged**
