### PR TITLE
Use core Random / opaque Fuzzer / Rosetree implementation

### PR DESCRIPTION
**Pull request by rtfeldman**
@mgold I did this before realizing you'd already made a `core-random` branch. This is slightly different in that it has an implementation of `independentSeed` that is bad but at least runs some logic, so it's slightly more realistic for perf testing.

Also based on Evan's recommendation (and the [official API design guidelines](http://package.elm-lang.org/help/design-guidelines#keep-tags-and-record-constructors-secret) - totally forgot they talked about this), I tried out not exposing the `Fuzzer` constructor directly. Personally I think it's nice, but curious to hear your thoughts!

Also renamed some things from `Test.Test` to `Test.Internal` and so forth.

Goal of this PR would be to be a starting point from which to performance optimize...on your end, 32-bit Pcg, and on my end, figuring out why `Claim` is still 5x faster than `fuzzTest`.

Thoughts?

### CODE REVIEW

**Comment by mgold** [comment]
I'm not going to have time to dig into 32-bit PCG until the weekend. Ideally it will get merged into core but since this shows that PCG still has some kinks to work out so it needs to remain third-party for awhile. I think we can tolerate a major release to change to using core to coincide with a release of core that changes the RNG, if necessary.

+1 to `Test.Internal` and moving `independentSeed` to Util.

I'm still not sold on making fuzzers opaque. It seems like we add a lot of overhead (API surface better represented by language constructs i.e. records) for the _ability_ to hide something later, without a concrete idea of what that would be. Hiding union types makes a lot of sense, but hiding type aliases is less useful. I'd be curious to hear what Evan said regarding this particular project and not just general patterns.

**Comment by rtfeldman** [comment]
Fair enough! Thoughts @evancz?

**Comment by evancz** [comment]
I think this is the correct move. In particular, this definition in `Fuzz.Internal` is the crucial change:

``` elm
type Fuzzer a
    = Fuzzer
        { generator : Generator a
        , shrinker : Shrinker a
        }
```

When Hassan was exploring this kind of testing, he mentioned a version that lazily unrolls random values, making it so the generation and shrinking were all part of one structure. I recall him saying it was even monadic so `map` and `andThen` would just work on a `Fuzzer` defined in that way, making it much easier to define custom stuff. Switching the implementation in this way does not need to break old code.

If you are talking about performance overhead, that is not a legitimate long-term concern. Elm is able to use the `newtype` optimization on any `type` with only one constructor. OCaml does this too. The reason Haskell needs `newtype` is because of laziness messing things up.

Point is, I think this is the right thing to do.

**Comment by rtfeldman** [comment]
Looks like Hassan actually got it working: see [this issue](https://github.com/TheSeamau5/elm-check/issues/10) and [the branch where he got it working](https://github.com/TheSeamau5/elm-check/blob/lazy/src/Check.elm)!

Based on his implementing [elm-rosetree](https://github.com/TheSeamau5/elm-rosetree) in order to use it for this, I'm betting he was basing his implementation on [this](http://reiddraper.com/writing-simple-check/) and [this](https://mail.haskell.org/pipermail/libraries/2013-November/021674.html) (walkthroughs on how to do it in Haskell).

**Comment by mgold** [comment]
Oh wow! One of the icky things with the current API is that you can't do `map` properly; you either need an inverse function or to not shrink. A similar problem stymies `andThen`. So, I still object to hiding "just" a record, but it sounds like this will work better with the rose tree, so that's totally worth hiding.

While I'd like to get the rosetree working for 1.0.0, yes we could ship it with the hidden record and add it later. We'll just have to remove `convert` from the API.

And no, I'm not concerned about the performance of wrapping and unwrapping, although long-term that would be a swell optimization.

**Comment by rtfeldman** [comment]
Okay, cool! I removed `convert` so that when we go RoseTree it can be a minor release that improves `Fuzz.map` and introduces `Fuzz.andThen`.

Merging so I can release. At this point we're only missing perf and RNG quality fixes!

**Comment by rtfeldman** [comment]
Released as [5.0.0](http://package.elm-lang.org/packages/project-fuzzball/test/5.0.0)!

**Comment by mgold** [comment]
Great! It'll be a major version bump to change back to Pcg, but that's fine while it's still project-fuzzball and not elm-test.

**Comment by rtfeldman** [comment]
Exactly!

**Pull request merged**
